version: '2'

services:
    tyk_redis:
        image: redis:latest
        hostname: redis
        ports:
            - "6379:6379"
        networks:
            gateway:
                aliases:
                    - redis
    tyk_mongo:
        image: mongo:latest
        command: ["mongod", "--smallfiles"]
        hostname: mongo
        ports:
            - "27017:27017"
        networks:
            gateway:
                aliases:
                    - mongo
    tyk_dashboard:
        image: tykio/tyk-dashboard:latest
        ports:
            - "3000:3000"
            - "5000:5000"
        volumes:
            - ./tyk_analytics.conf:/opt/tyk-dashboard/tyk_analytics.conf
        networks:
            - gateway
    tyk_pump:
        image: tykio/tyk-pump-docker-pub:latest
        networks:
            - gateway
        volumes:
            - ./pump.conf:/opt/tyk-pump/pump.conf
    tyk_gateway:
        image: tykio/tyk-gateway:latest
        ports:
            - "80:8080"
            - "8080:8080"
        volumes:
            - ./tyk.conf:/opt/tyk-gateway/tyk.conf
        networks:
            - gateway

networks:
    gateway:
