# see https://github.com/lonelycode/tyk_quickstart/blob/master/docker-compose.yml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: tyk-deployment
  name: tyk-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tyk
        env: prod
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
      - name: mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
      - name: tyk-dashboard
        image: tykio/tyk-dashboard:latest
        ports:
        - containerPort: 4000
        - containerPort: 5000
        volumeMounts:
        - mountPath: /git-conf
          name: git-config-volume
        command:
        - "/opt/tyk-dashboard/tyk-analytics"
        - "--c=/git-conf/tyk/conf/tyk_analytics.conf"
      - name: tyk-pump
        image: tykio/tyk-pump-docker-pub:latest
        volumeMounts:
        - mountPath: /git-conf
          name: git-config-volume
        command:
        - "/opt/tyk-pump/tyk-pump"
        - "--c=/git-conf/tyk/conf/tyk_pump.conf"
      - name: tyk-gateway
        image: tykio/tyk-gateway:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /git-conf
          name: git-config-volume
        command:
        - "/opt/tyk-gateway/tyk"
        - "--conf=/git-conf/tyk/conf/tyk_gateway.conf"
        - "--debug"
      volumes:
      - name: git-config-volume
        gitRepo:
          repository: "https://github.com/xeroSoftware/tyk"
      - name: mongo-persistent-storage
        gcePersistentDisk:
          pdName: tyk-mongo-disk
          fsType: ext4

